# Generated by Django 2.0.1 on 2018-04-01 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordbucket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation_text', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Like_and_dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes_like', models.IntegerField(default=0)),
                ('votes_dislike', models.IntegerField(default=0)),
                ('word_fk_forLandD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordbucket.Explanation')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(default='')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='explanation',
            name='word_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordbucket.Word'),
        ),
    ]
