# Generated by Django 2.0.1 on 2018-04-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordbucket', '0003_remove_word_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='explanation',
            old_name='word_fk',
            new_name='word',
        ),
        migrations.RenameField(
            model_name='like_and_dislike',
            old_name='word_fk_forLandD',
            new_name='explanation',
        ),
    ]
